version: "3"
services:
  libre1:
    build:
      context: .
  libre2:
    build:
      context: .
  libre3:
    build:
      context: .
  libre4:
    build:
      context: .
  libre5:
    build:
      context: .
  libre6:
    build:
      context: .
  libre7:
    build:
      context: .
  libre8:
    build:
      context: .
  libre9:
    build:
      context: .
  libre10:
    build:
      context: .
  balancer:
    image: "nginx:1.13.5-alpine"
    ports:
      - "6000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf